CREATE TABLE `business_profiles` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`client_id` integer NOT NULL,
	`business_name` text NOT NULL,
	`is_client` integer DEFAULT false NOT NULL,
	`searched_as` text DEFAULT '' NOT NULL,
	`rating` real,
	`review_count` integer,
	`category` text,
	`website` text,
	`has_hours` integer,
	`unclaimed` integer,
	`reviews_last_30_days` integer,
	`newest_review_days` integer,
	`reviews_sampled` integer DEFAULT 0 NOT NULL,
	`ok` integer DEFAULT true NOT NULL,
	`error` text,
	`captured_at` integer,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `serp_snapshots` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`client_id` integer NOT NULL,
	`location_id` integer,
	`query` text NOT NULL,
	`query_kind` text DEFAULT 'question' NOT NULL,
	`searched_from` text DEFAULT '' NOT NULL,
	`ai_overview_text` text DEFAULT '' NOT NULL,
	`ai_overview_sources` text DEFAULT '[]' NOT NULL,
	`client_in_ai_overview` integer DEFAULT false NOT NULL,
	`client_cited_in_ai_overview` integer DEFAULT false NOT NULL,
	`local_pack` text DEFAULT '[]' NOT NULL,
	`client_pack_position` integer,
	`organic` text DEFAULT '[]' NOT NULL,
	`client_organic_position` integer,
	`people_also_ask` text DEFAULT '[]' NOT NULL,
	`related_searches` text DEFAULT '[]' NOT NULL,
	`suggestions` text DEFAULT '[]' NOT NULL,
	`ads_count` integer DEFAULT 0 NOT NULL,
	`screenshot_path` text,
	`ok` integer DEFAULT true NOT NULL,
	`error` text,
	`captured_at` integer,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`location_id`) REFERENCES `locations`(`id`) ON UPDATE no action ON DELETE no action
);
