import { eq } from 'drizzle-orm'
import { openDb, schema } from '../db/raw'
import { resolveClient } from '../lib/resolve-client'
import { adapterFor } from '../ingest/adapters'
import { splitContent } from '../ingest/split'
import { auditGeo, countStats, countSuperlatives, readingEase, wordCount } from '../ingest/score'

/**
 * Pulls the client's site into the database and scores every paragraph.
 *
 * Only the WordPress adapter exists at present — Shopify and a generic crawler
 * arrive in step 3 of the plan, behind a shared interface.
 */
async function main() {
  const db = openDb()
  const client = resolveClient(db)

  const adapter = adapterFor(client)
  console.log(`ingesting ${client.name} (${client.domain}) via the ${adapter.name} adapter`)

  const wpPages = await adapter.fetchAll(client, (msg) => console.log(`  ${msg}`))
  console.log(`fetched ${wpPages.length} pages\n`)

  /**
   * Full re-ingest each run; these sites are small enough that incremental sync
   * is not worth the complexity.
   *
   * Order matters. Recommendations point at pages by foreign key, so they have
   * to go first or the delete fails outright. They are derived from page content
   * anyway, so they are regenerated by `npm run recommend` after this.
   */
  const existing = db.select().from(schema.pages).where(eq(schema.pages.clientId, client.id)).all()
  const staleRecs = db
    .delete(schema.recommendations)
    .where(eq(schema.recommendations.clientId, client.id))
    .run()
  for (const p of existing) {
    db.delete(schema.paragraphs).where(eq(schema.paragraphs.pageId, p.id)).run()
  }
  db.delete(schema.pages).where(eq(schema.pages.clientId, client.id)).run()

  if (staleRecs.changes > 0) {
    console.log(`cleared ${staleRecs.changes} recommendations tied to the old pages — re-run "npm run recommend"\n`)
  }

  let totalParagraphs = 0
  const geoOffenders: Array<{ slug: string; hits: number }> = []

  for (const wp of wpPages) {
    const { plainText, blocks } = splitContent(wp.contentHtml)
    const geo = auditGeo(
      [wp.slug, wp.title, wp.metaDescription, plainText].join(' '),
      client.wrongGeoTerms,
    )

    const inserted = db
      .insert(schema.pages)
      .values({
        clientId: client.id,
        externalId: wp.externalId,
        url: wp.url,
        slug: wp.slug,
        title: wp.title,
        metaDescription: wp.metaDescription,
        text: plainText,
        wordCount: wordCount(plainText),
        schemaTypes: JSON.stringify(wp.schemaTypes),
        pageType: wp.pageType,
        geoRefs: JSON.stringify(geo.terms),
        wrongGeoHits: geo.hits,
      })
      .returning({ id: schema.pages.id })
      .all()

    const pageId = inserted[0].id
    if (geo.hits > 0) geoOffenders.push({ slug: wp.slug, hits: geo.hits })

    if (blocks.length > 0) {
      db.insert(schema.paragraphs)
        .values(
          blocks.map((b) => ({
            pageId,
            sortOrder: b.sortOrder,
            heading: b.heading,
            text: b.text,
            wordCount: wordCount(b.text),
            statCount: countStats(b.text),
            hasCitation: b.hasLink,
            superlativeCount: countSuperlatives(b.text),
            readability: readingEase(b.text),
          })),
        )
        .run()
      totalParagraphs += blocks.length
    }
  }

  console.log(`stored ${wpPages.length} pages, ${totalParagraphs} paragraphs\n`)

  if (client.wrongGeoTerms.length === 0) {
    console.log('(no wrong-geography terms recorded for this client — geo audit skipped)')
    return
  }

  geoOffenders.sort((a, b) => b.hits - a.hits)
  const totalHits = geoOffenders.reduce((a, b) => a + b.hits, 0)
  console.log('=== GEO AUDIT: references to places outside the service area ===')
  console.log(`${geoOffenders.length} of ${wpPages.length} pages affected. ${totalHits} references total.`)
  for (const o of geoOffenders.slice(0, 10)) {
    console.log(`  ${o.hits.toString().padStart(4)}  /${o.slug}`)
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
