import { openDb } from '../db/raw'
import { resolveClient, clientLocations } from '../lib/resolve-client'
import { buildReportDocuments } from '../report/build'
import { arg, flag } from '../lib/args'

/**
 * Renders the two documents a run produces.
 *
 *   npx tsx src/scripts/report.ts --client=3
 *   npx tsx src/scripts/report.ts --client=3 --no-pdf
 *   npx tsx src/scripts/report.ts --client=3 --pdf-dir=~/Documents
 *
 * The audit is what the client is sent. The fix pack is every proposed change
 * in full, which is what a site the console cannot publish to needs — a repo, a
 * hand-built template, a platform with no write API.
 *
 * Both are written as HTML into the project and as PDFs onto the Desktop, so
 * the deliverable is somewhere a person can attach it to an email rather than
 * inside a folder they did not choose.
 *
 * Everything the documents contain is gathered in src/report/build.ts, which
 * the console calls too: a report generated by a run and one generated from the
 * dashboard have to be the same document.
 */

async function main() {
  const db = openDb()
  const client = resolveClient(db)
  const locations = clientLocations(db, client.id)

  const built = await buildReportDocuments(db, client, locations, {
    market: arg('market'),
    date: arg('date'),
    pdf: !flag('no-pdf'),
    pdfDir: arg('pdf-dir'),
  })

  const { data } = built
  console.log(`report written:   ${built.reportFile}`)
  console.log(`fix pack written: ${built.fixPackFile}`)
  console.log(`  client: ${client.name} (${client.businessType})`)
  console.log(`  headline: named in ${data.named} of ${data.totalAnswers} AI answers`)
  console.log(
    `  ${data.findings.length} findings (${data.findings.filter((f) => f.severity === 'critical').length} critical), ` +
      `${data.fixes.length} changes to make`,
  )
  console.log(`  ${data.evidence.length} answers embedded as evidence`)

  for (const pdf of built.pdfs) {
    if (pdf.ok) console.log(`  PDF: ${pdf.file} (${Math.round(pdf.bytes / 1024)} KB)`)
    else console.log(`  no PDF at ${pdf.file} — ${pdf.error}`)
  }
}

main()
