import fs from 'node:fs'
import path from 'node:path'
import { eq, inArray } from 'drizzle-orm'
import type { openDb } from '../db/raw'
import * as schema from '../db/schema'
import type { Client, ClientLocation } from '../lib/client'
import { renderReport, type ReportData } from './template'
import { renderFixPack } from './fix-pack'
import { htmlToPdf, type PdfResult } from '../lib/pdf'
import { REPORTS_DIR, fixPackFileFor, pdfNameFor, pdfOutputDir, reportFileFor } from '../lib/report-file'
import { isAnswer, mentionsClient } from '../analysis/parse'
import { RATING_THRESHOLDS } from '../config'
import { groupByMarket, marketKeyOf } from '../lib/markets'
import { hasBusinessSchema } from '../lib/schema-types'

/**
 * Everything the two client-facing documents are built from.
 *
 * Lifted out of the script that used to hold it so the console can produce the
 * same documents on a button press. A report generated from the dashboard and
 * one generated by a run have to be the same document — the alternative is an
 * operator sending a client whichever of the two happened to be newer.
 */

/** Keeps the file emailable — screenshots are the bulk of the size. */
const MAX_EMBEDDED_SCREENSHOTS = 3

function embedImage(relPath: string | null): string | undefined {
  if (!relPath) return undefined
  const abs = path.resolve(relPath)
  if (!fs.existsSync(abs)) return undefined
  const bytes = fs.readFileSync(abs)
  if (bytes.length > 2_000_000) return undefined
  return `data:image/png;base64,${bytes.toString('base64')}`
}

export type CollectOptions = { market?: string; date?: string }

export function collectReportData(
  db: ReturnType<typeof openDb>,
  client: Client,
  locations: ClientLocation[],
  opts: CollectOptions = {},
): ReportData {

  const pages = db.select().from(schema.pages).where(eq(schema.pages.clientId, client.id)).all()
  const pageIds = pages.map((p) => p.id)
  const paragraphs =
    pageIds.length > 0
      ? db.select().from(schema.paragraphs).where(inArray(schema.paragraphs.pageId, pageIds)).all()
      : []

  const prompts = db.select().from(schema.prompts).where(eq(schema.prompts.clientId, client.id)).all()
  const promptById = new Map(prompts.map((p) => [p.id, p]))
  const promptIds = prompts.map((p) => p.id)
  const runs =
    promptIds.length > 0
      ? db.select().from(schema.runs).where(inArray(schema.runs.promptId, promptIds)).all()
      : []
  const runIds = runs.map((r) => r.id)

  const mentions =
    runIds.length > 0
      ? db.select().from(schema.mentions).where(inArray(schema.mentions.runId, runIds)).all()
      : []
  const citations =
    runIds.length > 0
      ? db.select().from(schema.citations).where(inArray(schema.citations.runId, runIds)).all()
      : []

  const findings = db.select().from(schema.findings).where(eq(schema.findings.clientId, client.id)).all()

  const pageById = new Map(pages.map((p) => [p.id, p]))
  const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low'] as const
  const rank = (s: string) => {
    const i = SEVERITY_ORDER.indexOf(s as (typeof SEVERITY_ORDER)[number])
    return i === -1 ? SEVERITY_ORDER.length : i
  }

  const allFindings: ReportData['findings'] = findings
    .slice()
    .sort((a, b) => rank(a.severity) - rank(b.severity) || a.category.localeCompare(b.category))
    .map((f) => ({
      severity: (['critical', 'high', 'medium', 'low'].includes(f.severity)
        ? f.severity
        : 'medium') as ReportData['findings'][number]['severity'],
      category: f.category,
      issue: f.issue,
      currentText: f.currentText,
      proposedText: f.proposedText,
      evidence: f.evidence,
      where:
        f.targetType === 'page' && f.targetId != null
          ? (pageById.get(f.targetId)?.url ?? null)
          : null,
    }))

  /**
   * The whole fix list, highest priority first.
   *
   * Ordered the same way the console orders it, so a client reading the report
   * and an operator working through the fixes page are looking at one list in
   * one order rather than two lists that happen to overlap.
   */
  const recommendations = db
    .select()
    .from(schema.recommendations)
    .where(eq(schema.recommendations.clientId, client.id))
    .all()
    .sort((a, b) => b.priority - a.priority)

  const allFixes: ReportData['fixes'] = recommendations.map((r) => ({
    kind: r.kind,
    target: r.target,
    url: r.pageId != null ? (pageById.get(r.pageId)?.url ?? null) : null,
    currentValue: r.currentValue,
    proposedValue: r.proposedValue,
    reason: r.reason,
    placeholderCount: r.placeholderCount,
  }))
  // New pages are recommendations now; the old generated_pages table is dead.
  const generated = () => allFixes.filter((r) => r.kind === 'new_page')

  const okRuns = runs.filter(isAnswer)
  const named = okRuns.filter((r) => mentionsClient(r.answerText, client)).length

  const byEngine = new Map<string, { engine: string; ok: number; named: number }>()
  for (const r of okRuns) {
    const e = byEngine.get(r.engine) ?? { engine: r.engine, ok: 0, named: 0 }
    e.ok++
    if (mentionsClient(r.answerText, client)) e.named++
    byEngine.set(r.engine, e)
  }

  /**
   * Visibility split by trading area. A client with one market gets one row and
   * the report leaves the table out entirely, so this costs nothing there.
   */
  const markets = groupByMarket(locations)
  const marketKeyByLocation = new Map(locations.map((l) => [l.id, marketKeyOf(l)]))
  const marketTally = new Map(markets.map((m) => [m.key, { named: 0, total: 0 }]))
  for (const r of okRuns) {
    const locationId = promptById.get(r.promptId)?.locationId
    const key = locationId == null ? undefined : marketKeyByLocation.get(locationId)
    const row = key ? marketTally.get(key) : undefined
    if (!row) continue
    row.total++
    if (mentionsClient(r.answerText, client)) row.named++
  }

  const competitorCounts = new Map<string, number>()
  for (const m of mentions) {
    if (!m.isClient) competitorCounts.set(m.businessName, (competitorCounts.get(m.businessName) ?? 0) + 1)
  }

  const domainCounts = new Map<string, number>()
  for (const c of citations) domainCounts.set(c.domain, (domainCounts.get(c.domain) ?? 0) + 1)

  const rivals = db
    .select()
    .from(schema.competitors)
    .where(eq(schema.competitors.clientId, client.id))
    .all()
    .filter((c) => c.ok)
  const locals = rivals.filter((c) => !c.isNational && c.pageCount > 0)
  const avg = (f: (c: (typeof locals)[number]) => number) =>
    locals.length ? Math.round((locals.reduce((a, c) => a + f(c), 0) / locals.length) * 10) / 10 : 0

  const substantial = paragraphs.filter((p) => p.wordCount >= 40)
  const myWords = substantial.reduce((a, p) => a + p.wordCount, 0)
  const mySchema = new Set<string>()
  for (const p of pages) (JSON.parse(p.schemaTypes || '[]') as string[]).forEach((t) => mySchema.add(t))

  /**
   * The client's own side of the table, counted rather than assumed.
   *
   * Both of these were hardcoded to zero, which reads as a measurement and is
   * not one: a site with a page per town and an FAQ block on every one of them
   * was still reported as having neither, and the plan built on that told the
   * owner to create pages they already had.
   */
  const placeSlugs = locations.flatMap((l) => {
    const n = l.name.toLowerCase()
    return [n.replace(/\s+/g, '-'), n.replace(/\s+/g, '')]
  })
  const myCityPages = placeSlugs.length
    ? pages.filter((p) => placeSlugs.some((slug) => p.slug.toLowerCase().includes(slug))).length
    : 0
  // Counted the same way as a competitor's: a heading phrased as a question.
  const myFaqBlocks = paragraphs.filter((p) => /\?\s*$/.test(p.heading.trim())).length

  const gap: ReportData['gap'] = [
    { label: 'Total pages', client: pages.length, rivals: avg((c) => c.pageCount) },
    {
      label: 'Pages targeting a place you serve',
      note: 'the strongest signal in this data',
      client: myCityPages,
      rivals: avg((c) => c.cityPageCount),
    },
    {
      label: 'FAQ sections',
      note: 'the format AI assistants quote most often',
      client: myFaqBlocks,
      rivals: avg((c) => c.faqBlockCount),
    },
    {
      label: 'Facts and figures per 1,000 words',
      note: 'concrete numbers are the single biggest measured lever',
      client: myWords ? Math.round((substantial.reduce((a, p) => a + p.statCount, 0) / myWords) * 1000 * 10) / 10 : 0,
      rivals: avg((c) => c.statsPerThousand),
    },
    {
      label: 'Business details in the page code',
      note: 'how search engines confirm what this business is',
      client: hasBusinessSchema([...mySchema], client.businessType) ? 'Yes' : 'No',
      rivals: `${locals.filter((c) => c.hasLocalBusiness).length} of ${locals.length} have it`,
    },
    {
      label: 'Superlatives ("best", "#1")',
      note: 'research measures these as neutral to negative — fewer is better',
      client: paragraphs.reduce((a, p) => a + p.superlativeCount, 0),
      rivals: avg((c) => c.superlativeCount),
    },
  ]

  const evidence: ReportData['evidence'] = okRuns
    .filter((r) => promptById.get(r.promptId)?.intent === 'comparison')
    .slice(0, MAX_EMBEDDED_SCREENSHOTS)
    .map((r) => ({
      engine: r.engine,
      question: promptById.get(r.promptId)?.text ?? '',
      excerpt: r.answerText.slice(0, 700),
      image: embedImage(r.screenshotPath),
    }))

  const marketFallback = locations.length
    ? [...new Set(locations.map((l) => l.metro || l.name))].join(' and ')
    : 'online'

  const data: ReportData = {
    clientName: client.name,
    clientDomain: client.domain,
    businessType: client.businessType,
    hasGoogleProfile: client.gbpRating !== null || client.gbpUrl !== null,
    market: opts.market ?? marketFallback,
    generatedOn:
      opts.date ?? new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' }),
    named,
    totalAnswers: okRuns.length,
    engines: [...byEngine.values()],
    markets: markets.map((m) => ({
      label: m.label,
      named: marketTally.get(m.key)?.named ?? 0,
      total: marketTally.get(m.key)?.total ?? 0,
      locations: m.locations.map((l) => l.name),
    })),
    competitors: [...competitorCounts].sort((a, b) => b[1] - a[1]),
    citedDomains: [...domainCounts].sort((a, b) => b[1] - a[1]).slice(0, 10),
    cityLeaders: locals
      .filter((c) => c.cityPageCount > 0)
      .sort((a, b) => b.cityPageCount - a.cityPageCount)
      .map((c) => ({ domain: c.domain, cityPageCount: c.cityPageCount, pageCount: c.pageCount })),
    gap,
    rivalCount: locals.length,
    findings: allFindings,
    fixes: allFixes,
    pageCount: pages.length,
    paragraphCount: paragraphs.length,
    clientRenderedPages: pages.filter((p) => p.renderedWordCount < 50).length,
    phoneCount: client.phones.length,
    promptCount: prompts.filter((p) => p.isActive).length,
    wrongGeoPages: pages.filter((p) => p.wrongGeoHits > 0).length,
    wrongGeoHits: pages.reduce((a, p) => a + p.wrongGeoHits, 0),
    gbp: {
      rating: client.gbpRating,
      reviewCount: client.gbpReviewCount,
      hasWebsite: client.gbpHasWebsite,
    },
    thresholds: RATING_THRESHOLDS,
    evidence,
    generatedPageCount: generated().length,
  }

  return data
}


export type BuiltDocuments = {
  data: ReportData
  /** The audit as the client receives it. */
  reportHtml: string
  /** Every change in full, for a site nobody can publish to from here. */
  fixPackHtml: string
  pdfs: PdfResult[]
}

export type BuildOptions = CollectOptions & {
  /** Off for a quick regeneration, or on a machine with no bundled browser. */
  pdf?: boolean
  /** Overrides where the PDFs are written. Defaults to the Desktop. */
  pdfDir?: string
}

/**
 * Writes both documents, and their PDFs.
 *
 * Four files: the audit and the fix pack as HTML in the project, and a PDF of
 * each somewhere a person can actually attach it to an email. The HTML is
 * written first and unconditionally — a PDF is a copy, and a browser that
 * refuses to start must not cost the operator the report itself.
 */
export async function buildReportDocuments(
  db: ReturnType<typeof openDb>,
  client: Client,
  locations: ClientLocation[],
  opts: BuildOptions = {},
): Promise<BuiltDocuments & { reportFile: string; fixPackFile: string }> {
  const data = collectReportData(db, client, locations, opts)
  const reportHtml = renderReport(data)
  const fixPackHtml = renderFixPack(data)

  fs.mkdirSync(REPORTS_DIR, { recursive: true })
  const reportFile = reportFileFor(client.domain)
  const fixPackFile = fixPackFileFor(client.domain)
  fs.writeFileSync(reportFile, reportHtml, 'utf8')
  fs.writeFileSync(fixPackFile, fixPackHtml, 'utf8')

  const pdfs: PdfResult[] = []
  if (opts.pdf !== false) {
    const dir = opts.pdfDir ? path.resolve(opts.pdfDir) : pdfOutputDir()
    pdfs.push(await htmlToPdf(reportHtml, path.join(dir, pdfNameFor(client.domain, 'audit'))))
    // Only worth a second browser launch when there is something in it.
    if (data.fixes.length > 0) {
      pdfs.push(await htmlToPdf(fixPackHtml, path.join(dir, pdfNameFor(client.domain, 'fix-pack'))))
    }
  }

  return { data, reportHtml, fixPackHtml, pdfs, reportFile, fixPackFile }
}
